### ISSUE TITLE
Extensions per track is missing

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GPX#11]
I couldn't find a way (judging from the code) to add extensions to track.
Did I miss something?

**Comment by HarelM** [comment]
I did miss something, the following is needed in order to write extension per track:
`settings.ExtensionWriter.ConvertRouteExtension`
Although I think this is a copy-paste mistake? should it be `ConvertTrackExtension` in the following code:
https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/blob/316690d8eb5adac132a254f6efb54c0eaa79870e/NetTopologySuite.IO.GPX/GpxTrack.cs#L86

Probably worth adding this to the documentation when writing it.

**Comment by airbreather** [comment]
Yeah it was a copy-paste error on that line
