### ISSUE TITLE
Allow filling in a default "creator" value to work around invalid GPX files from legacy IHM

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GPX#23]
The world isn't perfect :-)
Following on some user feedback I got after publishing this to production.
The following error is a bit cryptic assuming the GPX version is 1.1.
https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/blob/83d9e579af2e6e8ffcf6f16ffdeeea7fb1ddc4be/src/NetTopologySuite.IO.GPX/GpxReader.cs#L119

You'll be able to get some examples from users in the issue they opened:
https://github.com/IsraelHikingMap/Site/issues/794

The problem is that creator is empty in these files.
I'm not sure how they got these files, but preventing opening a file because the creator field does not exist seems too rigid apparently...

**Comment by airbreather** [comment]
Wouldn't XSD validation fail for such files?

**Comment by HarelM** [comment]
It might be that .Net conversion from xsd to cs class doesn't obey the `required`? I'm not sure...
This is the gpx.cs generated from the xsd:
https://github.com/IsraelHikingMap/Site/blob/ac61da34ca613208d1fb76d07338ca0cbcdaf7fe/IsraelHiking.API/Gpx/gpx.cs

**Comment by HarelM** [comment]
Well, seems like I was naive to think that a generated class would be used to validate an xml :-)
I didn't have any checks on the GPX file on my site besides `XmlDeserialize` so it either worked and got the right data or failed while deserializing.
Having said that, I don't know if the fact that the GPX file doesn't have a creator is interesting to the end user.
Can `Read` accept a "don't throw" flag to workaround this? what do you think? should I send the users to the site they got the GPX from?

**Comment by airbreather** [comment]
> Having said that, I don't know if the fact that the GPX file doesn't have a creator is interesting to the end user.
> Can `Read` accept a "don't throw" flag to workaround this? what do you think? should I send the users to the site they got the GPX from?

The GPX schema documentation has this to say about `creator` being required:

> You must include the name or URL of the software that created your GPX document. This allows others to inform the creator of a GPX instance document that fails to validate.

I can improve the error message to help figure out what's wrong when there is some sort of a failure, but I do want this to throw `XmlException`, by default, in most or all cases that would cause a schema validation failure.

Perhaps `GpxReaderSettings` could have some flags to let you fill in a default creator if it turns out that these are being produced by an important non-compliant provider, but I'd appreciate it if we could try to figure out who's producing these invalid GPX files first.

**Comment by airbreather** [comment]
> While I don't like the fact that someone is generating an invalid GPX file, I can't tell my user to f$@k off, right? :-)

No, but there's a limit to how much hand-holding makes sense before the answer has to be "fix your data before uploading it".  In those cases (and this one, **at least** for now), you can do is catch specifically `XmlException` and have the handler run XSD validation to present the errors to the user.

**Comment by HarelM** [comment]
Well, seems I can only blame myself - the files where created by my code :-((( in a special scenario I forgot to add creator to the file.
Migrating to this library automatically fixes it, but I'll need to find a way to allow the user to open these damaged files... :-(

**Comment by HarelM** [comment]
Thanks! let me know when a new package is available.
Sorry for the trouble...

**Comment by airbreather** [comment]
> let me know when a new package is available.

@HarelM 0.3.0 is up on NuGet now.

**Comment by HarelM** [comment]
Thanks a lot for all the hard work! keep it up. I have published this change to my production site.
