### ISSUE TITLE
Ignore gpx version when parsing or get it from namespace

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GPX#28]
See GPX file from issue #27.
The problem there is that the version is the version of the app and not the version of the scheme.
GPX version can be inferred from the namespace in that case, or completely ignored when parsing.
Either way works...

**Comment by airbreather** [comment]
I'm going to replace `AllowMissingVersionAttribute` with `IgnoreVersionAttributeDiscrepancies` instead of adding an additional flag, so be advised that upgrading to 0.3.2 will require code changes.

**Comment by HarelM** [comment]
Thanks a lot!! Keep up the good work!
