### ISSUE TITLE
Override the time format

### ISSUE THREAD

**Issue by lorenh** [NetTopologySuite/NetTopologySuite.IO.GPX#31]
I would like to override the time format written out in the GPX to optionally include fractional seconds.

NetTopologySuite.IO.GPX currently writes out this:
```
<trkpt lat="49.632506" lon="-94.067506">
  <time>2017-10-11T13:34:27Z</time>
</trkpt>
```

And we would like it to be this:
```
<trkpt lat="49.632506" lon="-94.067506">
  <time>2017-10-11T13:34:27.603Z</time>
</trkpt>
```

In Helpers.cs I see a hard-coded string format.  Any way to override this?

```
        public static void WriteOptionalGpxElementValue(this XmlWriter writer, string localName, DateTime? valueUtc, TimeZoneInfo timeZoneInfo)
        {
            if (valueUtc.HasValue)
            {
                const string Format = "yyyy-MM-ddTHH:mm:ssK";
```

**Comment by lorenh** [comment]
I did a PR of one simple way you could do this:

https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/pull/32

**Comment by airbreather** [comment]
> optionally include fractional seconds.

Starting in 0.5.0, timestamps are now **always** written out with fractional seconds, if present.  If there are cases where you don't want fractional seconds, then please do one of the following:

- Use an input file that does not have any fractional seconds,
- Round the timestamps in-memory (`.WithTimestampUtc` / `.WithCreationTimeUtc`)
- Open a separate GitHub issue asking for the ability to opt-out.  I'll gladly do this if this is something that's actually needed, but my guess is that 0.5.0 is good enough.

Thanks for the report!

**Comment by lorenh** [comment]
Thanks for addressing so quickly.  The best solution is one that "just works" for a majority of users.
