### ISSUE TITLE
Infinite loop in reading GPX file

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite.IO.GPX#41]
I'm still debugging this, but I see that there are threads on my server that are using 100% of the CPU - i.e infinite loop.
I have created a dump file and opened it in visual studio.
I found two threads that are "stuck" on 100% CPU, both are inside function of this library.
Here is a screenshot of the dump when I opened it in visual studio:
The code that I'm using to read the gpx file can be seen here:
https://github.com/IsraelHikingMap/Site/blob/4cb8ade62604c6b5ded7f94d944bef1da29893e4/IsraelHiking.API/Gpx/SerializarionExtensions.cs#L108L120
![image](https://user-images.githubusercontent.com/3269297/88975759-7153e280-d2c3-11ea-8ce7-3a96188edc9b.png)
Any help would be appreciated.
I'm using version 1.1.0 as can be seen here:
https://github.com/IsraelHikingMap/Site/blob/4cb8ade62604c6b5ded7f94d944bef1da29893e4/IsraelHiking.API/IsraelHiking.API.csproj#L28L31
Unfortunately I don't have the relevant GPX file...

**Comment by HarelM** [comment]
Ok, I added some logic around the problematic code to catch problematic files and save them to the file system.
I found this file:
[Bad_File_132406542477521233.gpx.txt](https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/files/5005777/Bad_File_132406542477521233.gpx.txt)
I see that it does enter an infinite loop as the task that runs this code never finishes on my dev env.
I'll see if I can fork this repo and send a RP or just get more insights as to what caused this.
@airbreather, let me know if you have a few minutes to take a look at this as you'll probably find the root cause faster...

**Comment by HarelM** [comment]
See PR #42, feel free to review the code I wrote and let me know if I need to fix anything.
If this could be pushed to NuGet it would be extremely helpful.
I don't think I have an easy way to workaround this since .net core does not have a way to kill threads and I would like to avoid parsing part of the gpx xml to find out there are issues in it as it would mean I'll need to copy the code to my project...
This is currently running in production and causes threads hangs so I think it's a critical bug.
Getting permissions to this repository would also be nice :-)

**Comment by airbreather** [comment]
FYI, I'm addressing this now.  Your PR #42 is a great start, and my fix is going to be based on that, but it relaxes a little bit too much of the structure that `GpxReader` promises to obey for me to take it as-is.  Don't worry about updating that PR on my account, I'll build on top of it and merge once I'm satisfied.  I agree that this is a high-priority critical bug.

I do appreciate the failing tests, as they reveal the two actual bugs: this one (where an unexpected top-level child of the `gpx` element triggers an infinite loop) and, immediately after fixing that, another bug where the loop isn't terminating quite properly when the `metadata` element is the only child of the `gpx` element.

**Comment by airbreather** [comment]
Version 1.1.1 is on NuGet now, I have some non-critical things to fix up, which I'll get to after I'm done with my normal work.

**Comment by HarelM** [comment]
Thanks for pushing it! Keep up the good work!
I'm sure we'll meet in the near future with another invalid GPX example :-)
